const producto = [
    { 
    id: 1,
    title: "Sweater Rayado Blanco y Negro",
    price:2500,
    imagen:"/assets/img_0305i.png",
    stock: 6,
    categoria: "sweater",
     },
    {
        id: 2,
        price:3000 ,
        title:"Sweater Verde Militar" ,
        imagen:"/assets/img_0302i.png",
        stock: 4,
        categoria: "sweater",
    },
       {
            id: 3,
            price:3500 ,
            title:"Swater Gris con Volados" ,
            imagen:"/assets/img_0304i.png",
            stock: 5,
            categoria: "sweater",
        },
        {
            id: 4,
            price:2800,
            title:"Sweater Gris Manga Globo",
            imagen:"/assets/img_0299i.png",
            stock:7,
            categoria: "sweater",
        },
        {
            id: 5,
            price:3100,
            title:"Sweater Polera Manteca",
            imagen:"/assets/img_0303i.png",
            stock: 3,
            categoria: "sweater",
        },
        {
            id: 6,
            price:2800,
            title:"Sweater Blanco y Camel",
            imagen:"/assets/img_0297i.png",
            stock: 5,
            categoria: "sweater",
        },
        {
            id: 7,
            price:3500, 
            title:"Sweater rayado Negro y Rojo",
            imagen:"/assets/img_0298i.png",
            stock: 4,
            categoria: "sweater",
        },
        {
            id: 8,
            price:2500,
            title:"Remera Rosa de Tiritas",
            imagen:"/assets/img_0288v.png",
            stock: 3,
            categoria: "remera",
            },
        ]
            export default producto